import path from 'path'
import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import fs from 'fs'

const nodeBuiltins = [...builtins, ...builtins.map((mod) => `node:${mod}`)]


const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

// Gemini CLI installed-app OAuth secret: read from env / untracked secrets.local.json
// so it never lives in committed source. Empty when not supplied (public source / CI).
function resolveGeminiOauthClientSecret() {
  const fromEnv = process.env.GEMINI_OAUTH_CLIENT_SECRET
  if (typeof fromEnv === 'string' && fromEnv.trim()) return fromEnv.trim()
  try {
    const raw = fs.readFileSync(path.resolve('secrets.local.json'), 'utf8')
    const value = JSON.parse(raw).GEMINI_OAUTH_CLIENT_SECRET
    if (typeof value === 'string' && value.trim()) return value.trim()
  } catch {
    // no local secrets file — leave empty
  }
  return ''
}

const geminiOauthClientSecret = resolveGeminiOauthClientSecret()
console.info(
  geminiOauthClientSecret
    ? `[esbuild] GEMINI_OAUTH_CLIENT_SECRET injected (len ${geminiOauthClientSecret.length})`
    : '[esbuild] GEMINI_OAUTH_CLIENT_SECRET empty — Gemini Plan OAuth disabled in this build',
)

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...nodeBuiltins,
  ],
  format: 'cjs',
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
    'process.env.GEMINI_OAUTH_CLIENT_SECRET': JSON.stringify(
      geminiOauthClientSecret,
    ),
  },
  target: 'es2020',
  logLevel: 'info', // 'debug' for more detailed output
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  metafile: true,
})

if (prod) {
  const result = await context.rebuild()
  fs.writeFileSync('meta.json', JSON.stringify(result.metafile))
  process.exit(0)
} else {
  await context.watch()
}
